/*
 * Mail Encrypter Created by 13012555  
 *   
 */
package View;

import Controller.IEmailStrategy;
import Exceptions.MailException;
import javax.swing.JOptionPane;

/**
 *
 * The view used to collect the users email details.
 */
public class EmailView extends javax.swing.JFrame {

    //The strategy used to pass the email data.
    private IEmailStrategy _emailStrategy;
    
    private Boolean _password = false;

    /**
     * Constructor for the EmailView. Calls initComonents to initialise the view.
     * Also assigns the email strategy.
     * @param strat - The email strategy.
     */
    public EmailView(IEmailStrategy strat) {
        initComponents();
        _emailStrategy = strat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _submitDetailsButton = new javax.swing.JButton();
        _cancelButton = new javax.swing.JButton();
        _emailField = new javax.swing.JTextField();
        _passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        _submitDetailsButton.setText("OK");
        _submitDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _submitDetailsButtonActionPerformed(evt);
            }
        });

        _cancelButton.setText("Cancel");
        _cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _cancelButtonActionPerformed(evt);
            }
        });

        _emailField.setText("Email Address");
        _emailField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _emailFieldMouseClicked(evt);
            }
        });

        _passwordField.setText("jPasswordField1");
        _passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _passwordFieldMouseClicked(evt);
            }
        });
        _passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _passwordFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Email Address");

        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Enter your Outlook365 Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(_submitDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(_cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_emailField)
                    .addComponent(_passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_submitDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * 
     * When the user clicks on the submit button the entered details are sent via the email strategy. The view is also closed. 
     * Catches any MailExceptions if errors occur.
     */
    private void _submitDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__submitDetailsButtonActionPerformed

        try{
        String pass= new String(_passwordField.getPassword());
        _emailStrategy.setEmailAttributes(_emailField.getText(), pass);
        this.setVisible(false);
        _password = false;
        }
        catch(MailException e)
        {
            switch(e.getMessage())
            {
                case "CONNECTION_FAILURE": JOptionPane.showMessageDialog(null,"Could not connect.","Error",JOptionPane.WARNING_MESSAGE);break;
            }
        }
        
    }//GEN-LAST:event__submitDetailsButtonActionPerformed

    /**
     * 
     * When the user clicks the cancel button the view is set to not visible. 
     */
    private void _cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__cancelButtonActionPerformed
        this.setVisible(false);
        _password = false;
    }//GEN-LAST:event__cancelButtonActionPerformed

    private void _passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__passwordFieldActionPerformed

    }//GEN-LAST:event__passwordFieldActionPerformed

    
    /**
     * 
     * For usability, when the user clicks on the password field it clears the placeholder text.
     */
    private void _passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__passwordFieldMouseClicked
        if(_password == false)
        {
            _passwordField.setText("");
            _password = true;
        }
        
    }//GEN-LAST:event__passwordFieldMouseClicked

    
    /**
     * 
     * For usability, when the user clicks on the email field it clears the placeholder text.
     */
    private void _emailFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__emailFieldMouseClicked
       if(_emailField.getText().contains("Address"))
       {
           _emailField.setText("");
       }
    }//GEN-LAST:event__emailFieldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _cancelButton;
    private javax.swing.JTextField _emailField;
    private javax.swing.JPasswordField _passwordField;
    private javax.swing.JButton _submitDetailsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
